### ISSUE TITLE
Mise en paquet de smwct

### ISSUE THREAD

**Issue by b4-b4** [b4-b4/smwct#8]
Les Modifications Suivantes Ne Devront Être Apporté qu'À Partir Du Moment Où La Partie de Recherche Sera Fonctionnel
---
Pour l'instant, pour lancer *smwct* il faut écrire la fastidieuse commande `python path/to/run.py` qui varie en fonction de notre position dans le terminal. Un moyen de répondre à ce problème serait de faire de *Smwct* un paquet Python directement installable via `pip`. Cela nous permettrait d'appeler directement *smwct* avec le mot clé défini (_théoriquemnt `smwct`, mais pourquoi pas `wct` qui définit plus largement le projet : Wizard for the Computer Tree_).

**Comment by antoineB24** [comment]
faut choisir le nom , je veux bien le faire donc en pars avec smwct ?

**Comment by b4-b4** [comment]
Je partirais plutôt vers un `wct` pour "*Wizard for the Computer Tree*". Mais avant de le faire tu peux me dire comment tu vas le faire, comment on l’installe (pour un utilisateur lambda) et comment on le met à jour ?

**Comment by antoineB24** [comment]
pour un utilisateur lambda soit on cree un script que l'user va download et l'exec qui va tous config , soit on va faire un package `pip` via pypi voila un doc pour t'aider : https://realpython.com/pypi-publish-python-package/ mais je peux le faire si tu veux :)

**Comment by b4-b4** [comment]
Je ne suis pas contre que tu le fasses, mais répond à cette question : comment on le met à jour ce paquet ? Parce que le paquet sur GitHub et celui disponible sur PyPi sont deux choses différentes.

**Comment by antoineB24** [comment]
bon deja c'est possible c'est sur , il faut l'update en local (pas sur github) et c'est presque la meme chose que quand tu l'install , tu propose une release

**Comment by b4-b4** [comment]
Ok. Charge toi de la mise en ligne du paquet.

**Comment by antoineB24** [comment]
je veux dire quelle branch ? la branch search-finition ?

**Comment by b4-b4** [comment]
Je viens de pusher la dernière version de l'[explorer](https://github.com/b4-b4/smwct/blob/search-finition/src/module/explorer.py).

**Comment by antoineB24** [comment]
sur quelle branch ?

**Comment by b4-b4** [comment]
> je veux dire quelle branch ? la branch search-finition ? ou la branch main ?

Non mes la `main`, on mergera dessus quand l'explorer sera fini.

**Comment by antoineB24** [comment]
cela te convient c'est un test (pas le vrais package) : https://test.pypi.org/project/wct/0.0.1/ 

copie la commande qui te dit dans le site et dit moi si il y a des erreur (pour l'exec je ne suis pas sur que ca marche)

**Comment by antoineB24** [comment]
EDIT: cela ne marche pas (je l'ai teste) et c'est une version de teste ce n'est pas une version normal

**Comment by antoineB24** [comment]
bon j'ai trouve l'erreur pourrait tu renommer run.py par snwct.py 

alors parce que quand l'user va installer le package il pourra import run.py or il ne sait pas ce que fait run.py alors wue smwct oui

**Comment by antoineB24** [comment]
OK voila la version qui marche (ca donne une erreur mais c'est pas moi c'est le code)

**Comment by b4-b4** [comment]
Pourquoi la commande d'installation ne ressemble pas à `pip install smwct` ?

**Comment by antoineB24** [comment]
c'est un test le vrais ici: https://pypi.org/project/smwct/

**Comment by b4-b4** [comment]
Tu es le seul à pouvoir le mettre à jour ? Et es-tu propriétaire de ça paquet *(si c’est le cas ne quitte pas le projet spontanément, pour qu’on puiser mettre le paquet à nouveau en ligne)*.

**Comment by antoineB24** [comment]
oui
